"""update tables

Revision ID: 6cf7b847392e
Revises: 81d062fda935
Create Date: 2024-01-13 16:28:11.147531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6cf7b847392e"
down_revision: Union[str, None] = "81d062fda935"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("creator_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "tasks", "users", ["creator_id"], ["id"])
    op.add_column(
        "usertasksassociations",
        sa.Column("is_executor", sa.Boolean(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usertasksassociations", "is_executor")
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_column("tasks", "creator_id")
    # ### end Alembic commands ###
