"""add deadline

Revision ID: b1ef9575e8bb
Revises: 647908b9b696
Create Date: 2024-01-27 16:56:19.308177

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1ef9575e8bb"
down_revision: Union[str, None] = "647908b9b696"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("deadline", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "deadline")
    # ### end Alembic commands ###
