"""add delete cascade

Revision ID: e2a517941b47
Revises: 0f493c3a5de9
Create Date: 2024-01-21 23:29:14.254097

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2a517941b47"
down_revision: Union[str, None] = "0f493c3a5de9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks", "creator_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint("tasks_creator_id_fkey", "tasks", type_="foreignkey")
    op.create_foreign_key(
        None, "tasks", "users", ["creator_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.create_foreign_key(
        "tasks_creator_id_fkey", "tasks", "users", ["creator_id"], ["id"]
    )
    op.alter_column(
        "tasks", "creator_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
